### ISSUE TITLE
Account page UX needs improvements

### ISSUE THREAD

**Issue by the-j0k3r** [OpenUserCSS/openusercss.org#101] opened 2018-06-14 02:37 UTC
| Expected behaviour | Actual behaviour |
| ------------------ | ---------------- |
| What you expected the site to do | What the site actually did |
| issue 1 to be easy to use | its convoluted |
| issue 2 buttons ontop /attached to other elements | should be some consistent padding |

## Steps to Reproduce the Problem

  1. navigate to https://openusercss.org/account
  1. notice on top of page a button that reads <kbd>Save unlocked account details</kbd>
  1. Scroll to bottom, see email and password boxes on the left BELOW active sessions
  1. issue 1: edit any details anywhere and have long scroll back to top to press the <kbd>Save unlocked account details</kbd>
  1. issue 2: see on the email update box the <kbd>Resend verification email is attached to the input filed with NO padding.

## Environment details

  - Site version: 1.2.0 - 1.1.0 -  1.0.0 - 0.9.7
  - Browser and version: Firefox 66.0.2
  - Installed extensions: Stylus
  - Operating system: Win 10 pro

issue 1 Save button couldnt possibly be further from where action is.
![screenshot-2018-6-14 openusercss 1](https://user-images.githubusercontent.com/31389848/41388477-00735c20-6f84-11e8-8a00-2e761e6d531a.png)

issue 2 - Ide put that button right inside the input field :+1:  joking just add some padding to top?
![screenshot-2018-6-14 openusercss](https://user-images.githubusercontent.com/31389848/41388476-0053f34e-6f84-11e8-9bd5-cc328fbb9b24.png)

----

<details>
  <summary><strong>Stack trace</strong> (click to expand)</summary>

  ```
  {{trace here}}
  ```
</details>

**Comment by DecentM** [comment] 2018-06-14 16:44
It looks fine to me, can you check if your theme is causing this?  
The verification actually goes out instantly without having to save the page, I think this is part of the UX issues on the account page.

**Comment by the-j0k3r** [comment] 2018-06-14 16:50
> It looks fine to me, can you check if your theme is causing this?

No its not, default no theme is same.

**Comment by the-j0k3r** [comment] 2018-06-17 00:58
OK.. A solution for the button spacing is this.

```css
	.is-6 .button.is-brand-primary {
		top: 9px !important;
	}
```

And looks like much better.

![button-space](https://user-images.githubusercontent.com/31389848/41503682-db30bcc8-71d1-11e8-9e4b-539278c0291d.gif)

**Comment by DecentM** [comment] 2018-06-17 01:05
Thanks for the patch!  
I'm still unable to repoduce this however, it looks fine on both Chrome and Firefox. Before this, please find a specific circumstance that causes this to happen!  

![screenshot_20180617_030328](https://user-images.githubusercontent.com/4973610/41503721-40a20018-71db-11e8-93fe-1d71e9027c3e.png)

**Comment by the-j0k3r** [comment] 2018-06-17 01:11
Patch needs refining to traget that button specifically.

>Before this, please find a specific circumstance that causes this to happen!

How can I do that, it just happens.

**Comment by DecentM** [comment] 2018-06-17 01:15
I'm looking for some information that will help me reproduce the problem. Since it doesn't happen for me on any browser, there must be something different between our setups that's causing this to happen.  
I need some way to see why the button isn't positioned correctly on your screen to be able to fix this.  

Anything has the possibility to cause the styling on the page to misbehave would be useful, for example:
- Extensions
- Custom CSS themes
- Screen size

**Comment by the-j0k3r** [comment] 2018-06-17 01:19
This happens without and with below.

    Extensions: Stylus
    Custom CSS themes, GitHub Dark,  Stylus Deepdark,  OpenUSerCSS Deepdark, Gitter Inspired Dark and many others that dont apply to this site.
    Screen size  resolution 2560x1440p

**Comment by the-j0k3r** [comment] 2018-06-17 14:08
OK try this to duplicate the padding issue in FF66.0.2 Windows

[padding.png](https://postimg.cc/image/bj7xc2ght/)

**Comment by DecentM** [comment] 2018-06-17 16:15
There we go! I've been able to reproduce this. It only happens on Firefox on Windows, but the font settings don't matter.  
Apparently it doesn't handle line breaks well, I'll have to refactor that field to use flexbox like most of the rest of the site does.

**Comment by the-j0k3r** [comment] 2018-06-17 16:36
That too.

**Comment by the-j0k3r** [comment] 2018-06-22 21:58
@DecentM see this for side menu

https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_sidenav

**Comment by DecentM** [comment] 2018-06-26 16:47
Merged into https://github.com/OpenUserCSS/openusercss.org/issues/124

**Closed by DecentM** 2018-06-26 16:47 UTC
Labels: confirmed, enhancement, roadmap
