### ISSUE TITLE
Profile says I have 0 themes when I already uploaded 4

### ISSUE THREAD

**Issue by tkosamja** [OpenUserCSS/openusercss.org#37] opened 2018-01-01 12:24 UTC
When I uploaded the themes, everything was fine. But then I log out and in again and even though the themes are in the front page, they don't show up on my profile.

**Comment by DecentM** [comment] 2018-01-01 12:36
Do they come back if you refresh the profile page?

**Comment by tkosamja** [comment] 2018-01-01 12:47
No. They appear when I'm not logged in though

**Comment by DecentM** [comment] 2018-01-01 12:50
I think this is a regression into #31. Tomorrow is a forum day, but I'll try to track it down once and for all (tm)

**Comment by DecentM** [comment] 2018-01-01 12:59
As a temporary workaround while I'm fixing it, I'm setting the site to restart every 30 minutes. When it starts, it runs a routine I wrote that automatically recreates the missing links.

**Comment by DecentM** [comment] 2018-01-03 03:34
Linking this with #8, because testing will more easily ensure that this is properly fixed.

**Comment by DecentM** [comment] 2018-01-03 04:17
It turns out that this is not a regression into #31,  this is new

**Comment by DecentM** [comment] 2018-01-03 09:26
Should be fixed in c7f58987f253c08a932cf8fed7443d3765af00e5

**Closed by DecentM** 2018-01-03 09:26 UTC
Labels: bug, confirmed, in progress
