### ISSUE TITLE
Cant change username (pls allow hyphens and spaces too)

### ISSUE THREAD

**Issue by the-j0k3r** [OpenUserCSS/openusercss.org#94] opened 2018-06-12 09:15 UTC
| Expected behaviour | Actual behaviour |
| ------------------ | ---------------- |
| What you expected the site to do | What the site actually did |
| Should be able to change username| nothing happens |

>### Also please allow hyphens and spaces in names, currently at registration neither is allowed.

## Steps to Reproduce the Problem

  1. visit https://openusercss.org/account
  1. unlock the username field
  1. enter a new username
  1. press the button <kbd>Save unlocked account details</kbd>

## Environment details

  - Site version: 0.9.7 and 1.1.0
  - Browser and version: any
  - Installed extensions: not applicable
  - Operating system: not applicable

----

<details>
  <summary><strong>Stack trace</strong> (click to expand)</summary>

  ```
  {{trace here}}
  ```
</details>

**Comment by DecentM** [comment] 2018-06-12 16:47
Thanks for creating the issue!

**Comment by the-j0k3r** [comment] 2018-06-12 16:59
>Thanks for creating the issue!

Youre welcome :)

enhancement only? I thought you confirmed the bug, since it doesn't actually work at all :)

**Comment by DecentM** [comment] 2018-06-12 17:01
It's not a bug, since I originally set the validator to only allow alphanumeric characters. I categorise issues as bugs when the site works against the way I intended it to.  
Regardless, this shouldn't take much time to change :+1:

**Comment by the-j0k3r** [comment] 2018-06-12 17:04
>It's not a bug, since I originally set the validator to only allow alphanumeric characters

So if I could change the username to `blablabla` that would be perfectly valid and working as intended, except it doesnt let me change it AT ALL.

**Comment by the-j0k3r** [comment] 2018-06-12 17:09
Yep doesn't work

![nick-change](https://user-images.githubusercontent.com/31389848/41305690-9349f05a-6e6b-11e8-87db-d847af47fdf0.gif)

:zap: :ok_hand:

**Comment by DecentM** [comment] 2018-06-12 17:11
Ah, that's a new issue, it actually works and you should get a notification e-mail, but the UI doesn't show it worked in any way

**Comment by the-j0k3r** [comment] 2018-06-12 17:15
Not new issue its THE issue Ive described several times and been trying to explain you in all the chats and here for-EVER.

As for the enhancement I can separate that from the bug if you want.

**Comment by DecentM** [comment] 2018-06-12 17:18
The button spinning means that the username you put in passwd the validator. When you use a space (or other, non-alphanumeric characters), it doesn't spin and applies a red colour to the text input. This is why I said this is a different issue.  
I've got your issue clearly, it's already being tracked here and I'll fix it in a future update.

**Comment by the-j0k3r** [comment] 2018-06-12 19:52
>it actually works and you should get a notification e-mail

There is no indication that ANY message was sent anywhere for any reason, may I suggest a more standard approach and pop some notification so at least ppl are expecting to receive an email.

I dont check my emails every day, in fact not even weekly as I dont use email that often for anything, If Im expecting some system sent and email I may actually go check, which then I do.

**Comment by DecentM** [comment] 2018-06-16 00:59
All this should be fixed, let me know if you have any issues with it!

**Closed by DecentM** 2018-06-16 00:59 UTC
Labels: enhancement

**Comment by the-j0k3r** [comment] 2018-06-16 01:42
Excellent, works a treat.

How did you get an avatar on the website?

**Comment by DecentM** [comment] 2018-06-16 01:48
Currently, the site gets avatars from [Gravatar](https://gravatar.com). If you use the same e-mail address to register there as you used on OUC, your avatar should automatically be picked up and shown.
