### ISSUE TITLE
Unwanted warnings in the code

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#125] opened 2018-07-05 16:19 UTC
So for some reason when I paste my code for youtube-deepdark, the interpreter finds "problems" for no reason.
![screenshot_20180705_191306](https://user-images.githubusercontent.com/19552720/42335091-df7e54ec-8087-11e8-9db1-6f2b3a6537f5.png)
I am not even sure what this is supposed to be.
![screenshot_20180705_191333](https://user-images.githubusercontent.com/19552720/42335092-df9eef68-8087-11e8-9053-8703911dfaf9.png)
This `}` is for the whole @moz code. Stylus sure doesn't say anything about it. I even tested in vim too. The brackets are fine. 

Also I get a lot of `use of !important` warnings too, but hey. (yeah also that issue is still present DM)

**Comment by Martii** [comment] 2018-07-05 16:59
Dupe of #121

**Comment by RaitaroH** [comment] 2018-07-06 03:58
@Martii What about the `}`. Ignore that too? (not like it matters because I can't upload the theme anyway due to #111)

**Closed** 2018-07-06 03:58 UTC

**Comment by Martii** [comment] 2018-07-06 05:09
@RaitaroH 
It's just the linter in Ace giving a hint at what might be incorrect... if @DecentM can directly edit the linter portion of Ace he can remove the warning by adding the prefixed rule next to the real rule of `@document`... which will in turn removes the trailing warning. Usually in Ace it's a triangle with an exclamation point. It's just a hinter message that has been themed to a red circle with a line in it... presumably a "no entry for vehicular traffic" as seen at http://www.passmytheory.co.uk/learningcentre/signs04.aspx ;)

OUJS has this issue as well with the `GM_`\* API... we tell our people it's safe to ignore... eventually I might write a chore to add the GM_* API to Ace once... same could be done here on OUCSS if the package isn't directly editable... but maintaining that manually is a nuisance... just like the warning message. :smile_cat: Automatically would need to be a pre-job after the dependency was installed successfully... so a lot of error checking to make sure it's added *only once* to Ace per dependency install/update.
