### ISSUE TITLE
Newline in theme title causes an exception

### ISSUE THREAD

**Issue by JourneyOver** [OpenUserCSS/openusercss.org#58] opened 2018-01-09 17:48 UTC
Trying to post a new theme, and I keep running into the error "Theme versioning must be semantic" whenever I click save. The thing is is that my versioning is semantic..
  
![chrome_01-09-2018_11-48-36](https://user-images.githubusercontent.com/13910285/34735155-118325ec-f534-11e7-9d4b-0289f0d0870f.png)

**Comment by RaitaroH** [comment] 2018-01-09 18:07
Can't reproduce. Works for me. 
https://openusercss.org/theme/5a55049143ab7f0b005ba4e0

**Comment by DecentM** [comment] 2018-01-09 18:10
I can't reproduce this either. Can you give some details about your environment? I'm looking for these specifically: Operating system, browser and browser version, extensions that you think may interfere.

Looking at the font, it feels like something didn't load properly. Can you try with a different browser and in incognito mode?

**Comment by JourneyOver** [comment] 2018-01-09 18:26
The font thing is because of a userstyle I'm running.

Operating system: Windows 10 x64 bit - Latest updates on Fall Creators Update
browsers tested on: 

- Main browser test: Cent Browser Version 3.0.4.29 (Official Build) (64-bit) (Chromium 62.0.3202.94) -- Doesn't work (tested both with and without incognito mode)
- Second browser test: Google Chrome Version 63.0.3239.132 (Official Build) (64-bit) -- Doesn't work (Clean google chrome install)
- Third browser test: Firefox 57.0.4 (64-bit) -- Worked

**Comment by DecentM** [comment] 2018-01-09 18:28
I've never heard of Cent Browser, I'll see if I can reproduce it there.

**Comment by JourneyOver** [comment] 2018-01-09 18:32
you should be able to reproduce in normal google chrome as well, as it's happening even with that as I noted above and it was with a brand new install of the browser so no extensions or anything.

**Comment by DecentM** [comment] 2018-01-09 18:35
The only way I was able to get this so far is when I put a space somewhere in the box. Can you check if you have a space before or after the version number?

**Comment by RaitaroH** [comment] 2018-01-09 18:38
Can confirm that a space is the cause of this.

**Comment by JourneyOver** [comment] 2018-01-09 18:38
Nope no space before or after the version number at all.

**Comment by JourneyOver** [comment] 2018-01-09 18:46
So I sorta got it to work now...for some reason the autofilling of the description/version/name is causing the issue... If I go and manually type in the version number into the version area it doesn't throw the error above, but it does go and throw a whole new error...

```
browser.js:1 GraphQLError {message: "Syntax Error GraphQL request (4:27) Unterminated s…"Plex Fixes↵                             ^↵5: ",↵", locations: Array(1), path: undefined, nodes: undefined, source: Source, …}locations: Array(1)0: column: 27line: 4__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()length: 1__proto__: Array(0)message: "Syntax Error GraphQL request (4:27) Unterminated string.↵↵3:       theme(↵4:         title: "Plex Fixes↵                             ^↵5: ",↵"path: undefinednodes: undefinedoriginalError: undefinedpositions: [55]source: Source {body: "↵    mutation {↵      theme(↵        title: "Plex …↵  bio,↵  donationUrl↵↵        }↵      }↵    }↵  ", name: "GraphQL request", locationOffset: {…}}stack: "GraphQLError: Syntax Error GraphQL request (4:27) Unterminated string.↵↵3:       theme(↵4:         title: "Plex Fixes↵                             ^↵5: ",↵↵    at exports.syntaxError (https://openusercss.org/browser.js:1:1340190)↵    at https://openusercss.org/browser.js:1:1348232↵    at https://openusercss.org/browser.js:1:1348377↵    at Object.advanceLexer [as advance] (https://openusercss.org/browser.js:1:1348648)↵    at expect (https://openusercss.org/browser.js:1:1359326)↵    at parseArgument (https://openusercss.org/browser.js:1:1354137)↵    at many (https://openusercss.org/browser.js:1:1360120)↵    at parseArguments (https://openusercss.org/browser.js:1:1353949)↵    at https://openusercss.org/browser.js:1:1353708↵    at parseSelection (https://openusercss.org/browser.js:1:1353866)↵    at many (https://openusercss.org/browser.js:1:1360120)↵    at parseSelectionSet (https://openusercss.org/browser.js:1:1352751)↵    at parseOperationDefinition (https://openusercss.org/browser.js:1:1351880)↵    at https://openusercss.org/browser.js:1:1360811↵    at https://openusercss.org/browser.js:1:1364377↵    at exports.parse (https://openusercss.org/browser.js:1:1364501)↵    at parseDocument (https://openusercss.org/browser.js:1:1334555)↵    at gql (https://openusercss.org/browser.js:1:1336017)↵    at https://openusercss.org/browser.js:1:2949802↵    at tryCatch (https://openusercss.org/browser.js:1:2139546)↵    at Generator._invoke (https://openusercss.org/browser.js:1:2139151)↵    at Generator.prototype.(anonymous function) [as next] (https://openusercss.org/browser.js:1:2139830)↵    at step (https://openusercss.org/browser.js:1:2942500)↵    at https://openusercss.org/browser.js:1:2942703↵    at new Promise (<anonymous>)↵    at https://openusercss.org/browser.js:1:2942419↵    at https://openusercss.org/browser.js:1:2951172↵    at https://openusercss.org/browser.js:1:2972034↵    at tryCatch (https://openusercss.org/browser.js:1:2139546)↵    at Generator._invoke (https://openusercss.org/browser.js:1:2139151)↵    at Generator.prototype.(anonymous function) [as next] (https://openusercss.org/browser.js:1:2139830)↵    at step (https://openusercss.org/browser.js:1:2971239)↵    at https://openusercss.org/browser.js:1:2971442↵    at new Promise (<anonymous>)↵    at Store.exports.default.regeneratorRuntime.mark.commit (https://openusercss.org/browser.js:1:2971158)↵    at Store.<anonymous> (https://openusercss.org/browser.js:1:2973177)↵    at Array.<anonymous> (https://openusercss.org/browser.js:1:2885677)↵    at Store.dispatch (https://openusercss.org/browser.js:1:2894134)↵    at Store.dispatch (https://openusercss.org/browser.js:1:2892220)↵    at https://openusercss.org/browser.js:1:3052700↵    at Generator.next (<anonymous>)↵    at step (https://openusercss.org/browser.js:1:3048626)↵    at https://openusercss.org/browser.js:1:3048753↵    at <anonymous>"__proto__: Error
console.(anonymous function) @ browser.js:1
actionError @ browser.js:1
(anonymous) @ browser.js:1
(anonymous) @ browser.js:1
(anonymous) @ browser.js:1
Store._withCommit @ browser.js:1
Store.commit @ browser.js:1
Store.commit @ browser.js:1
(anonymous) @ browser.js:1
tryCatch @ browser.js:1
(anonymous) @ browser.js:1
prototype.(anonymous function) @ browser.js:1
step @ browser.js:1
(anonymous) @ browser.js:1
Promise rejected (async)
step @ browser.js:1
(anonymous) @ browser.js:1
exports.default.regeneratorRuntime.mark.commit @ browser.js:1
(anonymous) @ browser.js:1
(anonymous) @ browser.js:1
Store.dispatch @ browser.js:1
Store.dispatch @ browser.js:1
(anonymous) @ browser.js:1
step @ browser.js:1
(anonymous) @ browser.js:1
Promise resolved (async)
step @ browser.js:1
(anonymous) @ browser.js:1
(anonymous) @ browser.js:1
submit @ browser.js:1
boundFn @ browser.js:1
submit @ browser.js:1
invoker @ browser.js:1
fn._withTask.fn._withTask @ browser.js:1
wrapped @ browser.js:1
```

![chrome_01-09-2018_12-46-16](https://user-images.githubusercontent.com/13910285/34737206-1a34fe5c-f53b-11e7-9f0b-69179070df2b.png)

**Comment by JourneyOver** [comment] 2018-01-09 18:47
If you want to test with the actual theme I'm putting up you can find it here https://github.com/StylusThemes/Plex-Fixes/blob/master/style.user.css

**Comment by DecentM** [comment] 2018-01-09 18:52
Thanks for giving the example, I think this is due to the newline in the title.  
I edited the issue title to reflect this.

**Comment by DecentM** [comment] 2018-01-09 18:52
Although I have no idea how you got a newline in there :D

**Comment by JourneyOver** [comment] 2018-01-09 18:54
new line in the title :O when I paste and it does it's whole autofill stuff it doesn't add a newline to the title, but it does seem to add one the description for some reason.

**Comment by DecentM** [comment] 2018-01-09 18:59
The request fails in the Vue store, because the title somehow contains a newline. It's an easy fix, it's just that I never expected to have this issue.

**Comment by JourneyOver** [comment] 2018-01-09 19:03
Okay so new development, I decided to copy/paste the theme from my local copy, instead of copy/pasting from github and it worked O_o

**Comment by DecentM** [comment] 2018-01-09 19:06
Interesting. I'm pushing an attempt for a fix anyway, since it's ready.
I'll close this in the commit, but let me know if the version issue pops up again.

**Closed** 2018-01-09 19:06 UTC
Labels: bug, in progress

**Comment by JourneyOver** [comment] 2018-01-09 19:07
Alright I'll give it a few and then delete the theme and try to create it as new again on OUCSS and see if it still has the issue or not.

**Comment by DecentM** [comment] 2018-01-09 19:10
Actually, I just saw the code after checking it for the second time. You have these lines  
https://github.com/StylusThemes/Plex-Fixes/blob/master/style.user.css#L17  
in your theme, I think that trips it up.  
I expect this to be solved once I make the switch to [parse-usercss](https://github.com/StylishThemes/parse-usercss).

**Comment by JourneyOver** [comment] 2018-01-09 19:13
Hmm it could possibly be, but if that really was the cause then why would it work just fine copy/pasting my local version which has the same lines and everything?

**Comment by DecentM** [comment] 2018-01-09 19:20
That's a good question. If you still have both versions, can you diff them?

**Comment by JourneyOver** [comment] 2018-01-09 19:27
Okay so I did a diff on them, one major thing I noticed which is weird to say the least because the new lines are there when looking at the style on github...

This is copy paste word for word of the header --
Github --
```
/* ==UserStyle==
@name        Plex Fixes
@version     0.0.14
@description Bringing back plex to pre-3.0.0
@namespace   github.com/StylusThemes
@author      StylusThemes <https://github.com/StylusThemes>
@homepageURL https://github.com/StylusThemes/Plex-Fixes
@supportURL  https://github.com/StylusThemes/Plex-Fixes/issues
@updateURL   https://raw.githubusercontent.com/StylusThemes/Plex-Fixes/master/style.user.css
@license     CC-BY-SA-4.0
@advanced text PORT "Port Number" "32400"
@advanced text URL "Custom URL" "example.com"
@advanced text IMGURL "Custom Background Image for Discover Page *Works better if the image is a darker picture*" "http://example.com/example.jpg"
@advanced dropdown CastL "Cast List" {
CLY "Hover Effects" <<<EOT
a[class*=Tndv5]:hover,a[class*=Tndv5]:hover>div,a[class^=PrePlayCastCell-cardLink-]:hover,a[class^=PrePlayCastCell-cardLink-]:hover>div{transform:scale(1.07)} EOT;
CLH "Hide Cast List" <<<EOT
div[class*="3dQB5"],div[class^=PrePlayCastList-castList-]{display:none!important} EOT;
CLN "No Hover Effect & Don't Hide Cast List" <<<EOT
 EOT;
}
@advanced dropdown ExtrasM "Extras" {
EEY "Expand Movie Extras" <<<EOT
[class*="2NcGK"]>div:nth-child(2),[class*="2NcGK"]>div:nth-child(2)>[class*="2XznZ"]>div>div,[class^=PrePlayExtrasList-extrasHubCell-]>div:nth-child(2),[class^=PrePlayExtrasList-extrasHubCell-]>div:nth-child(2)>[class^=Measure-container-]>div>div{width:auto!important;height:auto!important}[class*="2NcGK"]>div:nth-child(2)>[class*="2XznZ"]>div>div>div,[class^=PrePlayExtrasList-extrasHubCell-]>div:nth-child(2)>[class^=Measure-container-]>div>div>div{display:inline-block;position:relative!important;margin:10px;transform:translate3d(10px,10px,0)!important} EOT;
EEH "Hide Extras" <<<EOT
div[class*="2NcGK"],div[class^=PrePlayExtrasList-extrasHubCell-]{display:none!important} EOT;
EEN "Don't Expand & Don't Hide" <<<EOT
 EOT;
}
@advanced dropdown RelatedL "Related Lists" {
RLY "Hide Related Lists" <<<EOT
div[class*="2fY8S"],div[class^=PrePlayRelatedList-relatedList-]{display:none!important} EOT;
RLN "Don't Hide" <<<EOT
 EOT;
}
@advanced dropdown PosterHE "Posters" {
PHEY "Hover Effects" <<<EOT
div[class^="MetadataPosterCard-cardContainer-"],div[class*="2gRcQ"]{box-shadow:0 6px 26px -2px #000;transition:all 350ms;-webkit-perspective:500px;perspective:500px}div[class^="MetadataPosterCard-cardContainer-"]:hover,div[class*="2gRcQ"]:hover{box-shadow:0 0 0 0 #000;transform:scale(.95) translateY(0px)}div[data-qa-id="hub--home.continue"] div[class^="MetadataPosterCard-cardContainer-"]:hover,div[data-qa-id="hub--home.continue"] div[class*="2gRcQ"]:hover{transform:scale(.97) translateY(-5px)}[class^="MetadataPhotoCell-photoContainer-"],[class*="1HkmQ"]{transition:all 350ms;-webkit-perspective:500px;perspective:500px}[class^="MetadataPhotoCell-photoContainer-"]:hover,[class*="1HkmQ"]{transform:scale(.95) translateY(0px)}[class^="MetadataPhotoCell-photo-"]:hover,[class*="Po3Kx"]:hover{box-shadow:none;transform:scale(1.02)}div[class^="MetadataPosterCard-cardContainer-"]:hover div[class^="PosterCardImg-imageContainer-"],div[class*="2gRcQ"]:hover div[class*="1Ar4M"]{filter: grayscale(50%) brightness(105%) contrast(220%)}div[class^="MetadataPosterCardOverlay-playCircle-"],div[class*="M67q6"]{border-radius:50%;width:50px;height:50px;font-size:18px;line-height:48px;color:hsla(0, 0%, 100%, .7);box-shadow:0 4px 16px -2px #000;transition:all 350ms;transform:translate(-50%, -50%) scale(.1)}div[class^="MetadataPosterCard-cardContainer-"]:hover div[class^="MetadataPosterCardOverlay-playCircle-"],div[class*="2gRcQ"]:hover div[class*="M67q6"]{transform:translate(-50%, -50%) scale(1.2)}div[class^="MetadataPosterCard-cardContainer-"]:hover [class^=plex-icon-play-],div[class*="2gRcQ"]:hover [class^=plex-icon-play-]{font-size:30px} EOT;
PHEN "No Hover Effects" <<<EOT
 EOT;
}
@advanced dropdown CompactSB "Contract The Sidebar To Save Screen Space [Expands Back Out On Hovering Over The Sidebar]" {
CSY "Yes" <<<EOT
.page-container{margin-left:0 !important}.sidebar-container{width:65px !important;transition:all 0.5s ease !important}.sidebar-container:hover{width:240px !important;transition:all 1.5s ease !important}[class^="SidebarLink-title"],[class^="SidebarServerLibraries-librariesTitle"],[class^="SidebarList-sidebarListHeader"],[class^="ServerMenuButton-serverMenuTitle-"],[class*="7WfGt"],[class*="3iqmv"],[class*="m1Kth"],[class*="cAqMG"]{font-size:0 !important}.sidebar-container:hover [class^="SidebarLink-title"],.sidebar-container:hover [class^="SidebarServerLibraries-librariesTitle"],.sidebar-container:hover [class^="SidebarList-sidebarListHeader"],.sidebar-container:hover [class*="7WfGt"],.sidebar-container:hover [class*="3iqmv"],.sidebar-container:hover [class*="m1Kth"]{font-size:12px !important;transition:all 2s ease !important}[class^="SidebarLibrariesActions-actions"],[class^="SidebarLink-children"],[class^="DisclosureArrow-disclosureArrow-"],[class*="2eVPc"],[class*="7pc_H"],[class*="1sBFv"]{display:none !important}.sidebar-container:hover [class^="SidebarLibrariesActions-actions"],.sidebar-container:hover [class^="SidebarLink-children"],.sidebar-container:hover [class^="DisclosureArrow-disclosureArrow"],.sidebar-container:hover [class*="2eVPc"],.sidebar-container:hover [class*="7pc_H"],.sidebar-container:hover [class*="1sBFv"]{display:inline-block !important;transition:all 2s ease !important}.sidebar-container:hover [class^="ServerMenuButton-serverMenuTitle-"],.sidebar-container:hover [class*="cAqMG"]{font-size:14px !important;transition:all 3s ease !important}[class^="SidebarLibraryItem-action"],[class*="2AHiQ"]{width:0 !important} EOT;
CSN "No" <<<EOT
 EOT;
}
==/UserStyle== */
```

and this is my local copy --
```
/* ==UserStyle==
@name        Plex Fixes
@version     0.0.14
@description Bringing back plex to pre-3.0.0
@namespace   github.com/StylusThemes
@author      StylusThemes <https://github.com/StylusThemes>
@homepageURL https://github.com/StylusThemes/Plex-Fixes
@supportURL  https://github.com/StylusThemes/Plex-Fixes/issues
@updateURL   https://raw.githubusercontent.com/StylusThemes/Plex-Fixes/master/style.user.css
@license     CC-BY-SA-4.0

@advanced text PORT "Port Number" "32400"
@advanced text URL "Custom URL" "example.com"
@advanced text IMGURL "Custom Background Image for Discover Page *Works better if the image is a darker picture*" "http://example.com/example.jpg"

@advanced dropdown CastL "Cast List" {
CLY "Hover Effects" <<<EOT
a[class*=Tndv5]:hover,a[class*=Tndv5]:hover>div,a[class^=PrePlayCastCell-cardLink-]:hover,a[class^=PrePlayCastCell-cardLink-]:hover>div{transform:scale(1.07)} EOT;
CLH "Hide Cast List" <<<EOT
div[class*="3dQB5"],div[class^=PrePlayCastList-castList-]{display:none!important} EOT;
CLN "No Hover Effect & Don't Hide Cast List" <<<EOT
 EOT;
}

@advanced dropdown ExtrasM "Extras" {
EEY "Expand Movie Extras" <<<EOT
[class*="2NcGK"]>div:nth-child(2),[class*="2NcGK"]>div:nth-child(2)>[class*="2XznZ"]>div>div,[class^=PrePlayExtrasList-extrasHubCell-]>div:nth-child(2),[class^=PrePlayExtrasList-extrasHubCell-]>div:nth-child(2)>[class^=Measure-container-]>div>div{width:auto!important;height:auto!important}[class*="2NcGK"]>div:nth-child(2)>[class*="2XznZ"]>div>div>div,[class^=PrePlayExtrasList-extrasHubCell-]>div:nth-child(2)>[class^=Measure-container-]>div>div>div{display:inline-block;position:relative!important;margin:10px;transform:translate3d(10px,10px,0)!important} EOT;
EEH "Hide Extras" <<<EOT
div[class*="2NcGK"],div[class^=PrePlayExtrasList-extrasHubCell-]{display:none!important} EOT;
EEN "Don't Expand & Don't Hide" <<<EOT
 EOT;
}

@advanced dropdown RelatedL "Related Lists" {
RLY "Hide Related Lists" <<<EOT
div[class*="2fY8S"],div[class^=PrePlayRelatedList-relatedList-]{display:none!important} EOT;
RLN "Don't Hide" <<<EOT
 EOT;
}

@advanced dropdown PosterHE "Posters" {
PHEY "Hover Effects" <<<EOT
div[class^="MetadataPosterCard-cardContainer-"],div[class*="2gRcQ"]{box-shadow:0 6px 26px -2px #000;transition:all 350ms;-webkit-perspective:500px;perspective:500px}div[class^="MetadataPosterCard-cardContainer-"]:hover,div[class*="2gRcQ"]:hover{box-shadow:0 0 0 0 #000;transform:scale(.95) translateY(0px)}div[data-qa-id="hub--home.continue"] div[class^="MetadataPosterCard-cardContainer-"]:hover,div[data-qa-id="hub--home.continue"] div[class*="2gRcQ"]:hover{transform:scale(.97) translateY(-5px)}[class^="MetadataPhotoCell-photoContainer-"],[class*="1HkmQ"]{transition:all 350ms;-webkit-perspective:500px;perspective:500px}[class^="MetadataPhotoCell-photoContainer-"]:hover,[class*="1HkmQ"]{transform:scale(.95) translateY(0px)}[class^="MetadataPhotoCell-photo-"]:hover,[class*="Po3Kx"]:hover{box-shadow:none;transform:scale(1.02)}div[class^="MetadataPosterCard-cardContainer-"]:hover div[class^="PosterCardImg-imageContainer-"],div[class*="2gRcQ"]:hover div[class*="1Ar4M"]{filter: grayscale(50%) brightness(105%) contrast(220%)}div[class^="MetadataPosterCardOverlay-playCircle-"],div[class*="M67q6"]{border-radius:50%;width:50px;height:50px;font-size:18px;line-height:48px;color:hsla(0, 0%, 100%, .7);box-shadow:0 4px 16px -2px #000;transition:all 350ms;transform:translate(-50%, -50%) scale(.1)}div[class^="MetadataPosterCard-cardContainer-"]:hover div[class^="MetadataPosterCardOverlay-playCircle-"],div[class*="2gRcQ"]:hover div[class*="M67q6"]{transform:translate(-50%, -50%) scale(1.2)}div[class^="MetadataPosterCard-cardContainer-"]:hover [class^=plex-icon-play-],div[class*="2gRcQ"]:hover [class^=plex-icon-play-]{font-size:30px} EOT;
PHEN "No Hover Effects" <<<EOT
 EOT;
}

@advanced dropdown CompactSB "Contract The Sidebar To Save Screen Space [Expands Back Out On Hovering Over The Sidebar]" {
CSY "Yes" <<<EOT
.page-container{margin-left:0 !important}.sidebar-container{width:65px !important;transition:all 0.5s ease !important}.sidebar-container:hover{width:240px !important;transition:all 1.5s ease !important}[class^="SidebarLink-title"],[class^="SidebarServerLibraries-librariesTitle"],[class^="SidebarList-sidebarListHeader"],[class^="ServerMenuButton-serverMenuTitle-"],[class*="7WfGt"],[class*="3iqmv"],[class*="m1Kth"],[class*="cAqMG"]{font-size:0 !important}.sidebar-container:hover [class^="SidebarLink-title"],.sidebar-container:hover [class^="SidebarServerLibraries-librariesTitle"],.sidebar-container:hover [class^="SidebarList-sidebarListHeader"],.sidebar-container:hover [class*="7WfGt"],.sidebar-container:hover [class*="3iqmv"],.sidebar-container:hover [class*="m1Kth"]{font-size:12px !important;transition:all 2s ease !important}[class^="SidebarLibrariesActions-actions"],[class^="SidebarLink-children"],[class^="DisclosureArrow-disclosureArrow-"],[class*="2eVPc"],[class*="7pc_H"],[class*="1sBFv"]{display:none !important}.sidebar-container:hover [class^="SidebarLibrariesActions-actions"],.sidebar-container:hover [class^="SidebarLink-children"],.sidebar-container:hover [class^="DisclosureArrow-disclosureArrow"],.sidebar-container:hover [class*="2eVPc"],.sidebar-container:hover [class*="7pc_H"],.sidebar-container:hover [class*="1sBFv"]{display:inline-block !important;transition:all 2s ease !important}.sidebar-container:hover [class^="ServerMenuButton-serverMenuTitle-"],.sidebar-container:hover [class*="cAqMG"]{font-size:14px !important;transition:all 3s ease !important}[class^="SidebarLibraryItem-action"],[class*="2AHiQ"]{width:0 !important} EOT;
CSN "No" <<<EOT
 EOT;
}
==/UserStyle== */
```

The only difference between the two on my diff checker is that all the new lines are literally gone when copy/pasting the theme from github for some reason.

**Comment by JourneyOver** [comment] 2018-01-09 19:32
so this currently just leads me to think that there is something going on with github in the end, as I have now noticed two separate issues.. one with copy/pasting from github (deleting new lines when there are new lines), and the second that it's for some odd reason new lines are being created out of no where even if they weren't there before,.

**Comment by JourneyOver** [comment] 2018-01-09 19:38
Just tested going into the edit page for the style on github and copy/pasting it from there and it worked as well when upping to OUCSS... (which of course included the new lines where they are supposed to be...) so I believe that pretty much confirms that it's an issue with github copy/pasting from the blob..

**Comment by DecentM** [comment] 2018-01-09 19:51
Did you copy from the raw version, or the one where the surrounding UI exists?

**Comment by JourneyOver** [comment] 2018-01-09 19:54
Surrounding UI. 
Raw doesn't have the problem..

But it's weird though because I've never had this problem before when copy/pasting from the surrounding UI instead of the raw.

**Comment by DecentM** [comment] 2018-01-09 19:57
They probably changed something that caused this. It never occurred to me because I always copied from the raw. I think this should be in /help.

**Comment by JourneyOver** [comment] 2018-01-09 20:01
I usually always copy from local if it's something I'm working on, but I didn't have my editor up at the time and I didn't feel like browsing through explorer to get to the style when I already had github up xD but at least we might have figured out the full problem now on what was causing this issue.
