### ISSUE TITLE
Emails to Outlook hosted domains aren't delivered

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#2] opened 2017-12-27 06:27 UTC
Ok so I made an account in the hopes I could upload something XD
First of all I did not get any email notification. Also I will wait for more account options such as change the avatar image, name, password, email etc.

Also I know uploading is coming soon so I will wait for that. Also, please let me link the themes to github so I won't have to reupload every time. A link to the READ.ME would also be nice.

I am even willing to make a DeepDark theme for your site. With all my color picking options and so on. Would be cool to have like a DuckDuckGo sorta setting going on were you can change the site's theme.

**Comment by DecentM** [comment] 2017-12-27 23:28
I'm actually working on account detail changes as we speak, and it should be done tomorrow at the latest, I think.
I just tried creating a new account, and the e-mail arrived to both self hosted, and Gmail addresses. Can you check if it maybe landed in your spam folder?
Linking to GH is a really cool idea, I've noted it down, and it'll be implemented after I get the core functionality done.
I originally thought the same, but I think having a feature where people can create lists would be better, but you can already just search the site name and it should come up.

**Comment by jerone** [comment] 2017-12-27 23:35
> I just tried creating a new account, and the e-mail arrived to both self hosted, and Gmail addresses. Can you check if it maybe landed in your spam folder?

Actually, I'm having the same issue. Never received an confirmation e-mail. Not even after pressing the confirmation button. I also checked my spam-folder. My e-mail is just a normal Hotmail account. I was able to login successfully.



> Linking to GH is a really cool idea, I've noted it down, and it'll be implemented after I get the core functionality done.

+1 on a GitHub connection.

**Comment by DecentM** [comment] 2017-12-28 00:06
I can now reproduce the email issue.
It looks like that the e-mail server I use is blacklisted by them.
I'll try contacting them and asking if they can add an exception, because I suspect that they blocked an entire range of IP addresses. Any other e-mail service should work in the meantime.

The only thing the verification restricts right now is posting themes, so that in cases like this, you can request a new verification message.

**Comment by RaitaroH** [comment] 2017-12-28 06:25
@DecentM It seems that the emails did arrive in my spam (now I don't remember if I checked or not). Unfortunately for me now the verification fails... most likely because I waited too long. I get:
`E-mail address verification failed`

Oh and is not actually `one day` tho. I did verify the link today earlier than the date the email arrived XD

Also trying to login gives me:
`Cannot read property 'length' of undefined`

**Comment by DecentM** [comment] 2017-12-28 06:49
The generated token is currently set to be valid for 24 hours. I think that the wording could be better to be more descriptive though.

What do you mean by verifying earlier than the arrival date?

Yeah, that's what happens when I push an update too quickly, sorry about that. I've created https://github.com/OpenUserCSS/openusercss.org/issues/4 for it, it should be fixed soon.
While it's fine this way, it would be better if you created a new issue separately in cases like this. It's easier to track and manage.

**Comment by DecentM** [comment] 2017-12-28 07:08
Ironically enough, Microsoft's tool to request whitelisting is down due to some DNS error. I'll try again tomorrow, or until it goes up again.

**Comment by DecentM** [comment] 2017-12-30 10:07
Here's what I got so far:
I don't know if it's just not working for me, but their form for applying for delisting has been constantly down: https://support.live.com/eform.aspx?productKey=edfsmsbl3&ct=eformts&scrx=1
They also have a form at sender.office.com, but that's also returning an error once it's submitted.

I think this has been ongoing for a while, because their support forum is filled with angry posts about this for about a year now.

If anyone has any ideas, or if it works for you, please let me know!

**Comment by jerone** [comment] 2017-12-30 11:50
I have no experience with mails not getting delivered. Our custom domains always worked. Maybe you can find something useful here: https://mail.live.com/mail/troubleshooting.aspx & https://www.hmailserver.com/forum/viewtopic.php?f=21&t=29763

**Comment by jerone** [comment] 2017-12-30 12:01
BTW, the confirmation mail from the forum is also never delivered.

**Comment by jerone** [comment] 2018-01-05 21:12
@DecentM Is it possible to manually confirm my account? I can't use the site at all right now.

**Comment by DecentM** [comment] 2018-01-05 21:13
Wait, can you not even log in?

**Comment by DecentM** [comment] 2018-01-05 21:14
If you can, you should be able to change your e-mail address and verify that one.
If you can't log in, that's a new bug.

**Comment by jerone** [comment] 2018-01-05 21:16
I can login, but I just can't do anything else (create theme or post). 

All my e-mails are Microsoft accounts (@live.nl, @hotmail.com, @msn.com).

**Comment by DecentM** [comment] 2018-01-05 21:25
That's quite a predicament. Try the forums again please!

**Comment by DecentM** [comment] 2018-05-01 06:26
I've been working with Microsot this last week, and they let me know they implemented mitigation for my sending IP. I just tested with a free outlook.com account and I was able to get e-mails, so (finally) I'll close this issue.  

@jerone Can you test to see if you're able to receive e-mails now?
Also, shoutouts to @dsgnr for getting me started on the right path!

**Closed by DecentM** 2018-05-01 06:26 UTC
Labels: blocked
