### ISSUE TITLE
Screenshot keeps disappearing and reappearing

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#11] opened 2017-12-29 15:57 UTC
So as the title says.

Example:
https://openusercss.org/theme/5a4605de961b8c0b001f2476

**Comment by RaitaroH** [comment] 2017-12-29 16:05
@Mottie noticed:
`looking at the HTML, I see <div class="flickity-slider" style="left: 0px; transform: translateX(0%);"></div> (an empty slider)`

**Comment by DecentM** [comment] 2017-12-29 20:03
I can confirm this. Without looking too much into this, I think that the encoded space trips it up, but not sure yet.

**Comment by DecentM** [comment] 2017-12-29 21:20
I figured out that this only happens when the visit is a reload. It doesn't happen when arriving to the slider from another page (and it's a single page navigation).

**Comment by DecentM** [comment] 2017-12-30 03:10
Quick update: This happens because when the page is loaded, the viewed theme variable is empty, which is then later filled in from the API.
However, Flickity is initialized instantly after the component is mounted.

**Comment by DecentM** [comment] 2017-12-30 04:10
Fixed in https://github.com/OpenUserCSS/openusercss.org/commit/90f16c8f65f9ea5e1b68271ede55c1ca8bdf51c2.
I'm closing this issue, but let me know if it's not working still.

**Closed by DecentM** 2017-12-30 04:10 UTC
Labels: bug, confirmed, in progress

**Comment by RaitaroH** [comment] 2017-12-30 06:08
Seems to be fixed now. Thanks.
