### ISSUE TITLE
Themes get rated automatically after upload. Also appear under popular

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#57] opened 2018-01-09 14:25 UTC
![image](https://user-images.githubusercontent.com/19552720/34725427-8fe55228-f559-11e7-9602-354d07a3aadb.png)
![image](https://user-images.githubusercontent.com/19552720/34725446-9e3d6202-f559-11e7-8be9-fdb60ee5bd28.png)
![image](https://user-images.githubusercontent.com/19552720/34725466-aafe80f2-f559-11e7-9c74-999c82113c63.png)

**Comment by RaitaroH** [comment] 2018-01-09 14:26
Maybe is my reputation...
XD

**Comment by DecentM** [comment] 2018-01-09 16:49
Can confirm, the issue is in the API, in the logic that loads popular themes.

**Comment by DecentM** [comment] 2018-01-09 16:49
...and possibly latest themes as well

**Comment by DecentM** [comment] 2018-01-12 16:00
Delaying this in favour of #67

**Comment by DecentM** [comment] 2018-06-10 18:57
This should be fixed with 1.0.0. I'll close this issue, but if it still persists for you, please let me know!

**Closed by DecentM** 2018-06-10 18:57 UTC
Labels: bug, confirmed
